---
title: "Bachelor_clean"
author: "Julie Svinth Nielsen"
date: "24/11/2021"
output: html_document
---



```{r}


library(tidyverse)
library(readr)
library(dplyr)
library(lme4)
library(tidyr)
library(ggpubr)
library(rstatix)
library(coin)
library(cowplot) 
library(lme4) 
library(sjPlot) 
library(sjmisc) 
library(effects)
library(sjstats) 
library(ggthemes)
library(patchwork)
library(plotrix)
```

```{r}


df_overall <- read_csv("df_overall.csv") # containing all interventions with both inspiration versions
df <- read_csv("df.csv") #containing all interventions minus inspiration products out in the store 


```



```{r}

# Load in data
df_w_1 <- read_csv("df_w_1.csv")
df_w_2 <- read_csv("df_w_2.csv")
df_w_3 <- read_csv("df_w_3.csv")



# Statistical summaries of difference
summary(df_w_1$diff)
summary(df_w_2$diff)
summary(df_w_3$diff)



library(ggpubr)
ggboxplot(df_w_1$diff, 
          ylab = "difference", xlab = FALSE,
          ggtheme = theme_minimal())


ggboxplot(df_w_2$diff, 
          ylab = "difference", xlab = FALSE,
          ggtheme = theme_minimal())


ggboxplot(df_try$diff_con, 
          ylab = "difference", xlab = FALSE,
          ggtheme = theme_minimal())


```


```{r}



# Hypothesis 1




# Visualizing
bxp_w_1 <- ggboxplot(
  df_w_1$diff, width = 0.5, add = c("mean", "jitter"), 
  ylab = "Difference", xlab = "Labeling"
  )+
  ggtitle("Boxplot of Label Intervention")+
  theme_solarized()


bxp_w_1_out <- ggboxplot(
  df_w_1_out$diff, width = 0.5, add = c("mean", "jitter"), 
  ylab = "Difference", xlab = "Labeling"
  )+
  ggtitle("Boxplot of Label Intervention")+
  theme_solarized()

bxp_w_1 # one huge outlier is heavily influencing the data, thus removed

bxp_w_1_out 

df_w_1_out %>% 
  get_summary_stats(diff, type = "median_iqr")



# Normality
ggqqplot(df_w_1, x = "diff") # Not normal
ggqqplot(df_w_1_out, x = "diff") # Not normal


gghistogram(df_w_1_out, x = "diff", y = "..density..", 
            fill = "steelblue",bins = 10, add_density = TRUE)


# Using one-tailed one-sample  Wilcoxon test 
wilcox.test(df_w_1_out$diff, mu = 0, alternative = "greater")




# Effect size 
df_w_1_out %>%  wilcox_effsize(diff ~ 1, mu = 0, alternative = "greater") # small effect size





```


```{r}
# Hypothesis 2



# Visualizing
bxp_w_2 <- ggboxplot(
  df_w_2$diff, width = 0.5, add = c("mean", "jitter"), 
  ylab = "Difference", xlab = "Nudging"
  )+
  ggtitle("Boxplot of Nudging Intervention")+
  theme_solarized()

bxp_w_2

df_w_2 %>% 
  get_summary_stats(diff, type = "mean_sd") 



# Normality
ggqqplot(df_w_2, x = "diff")
df_w_2 %>% shapiro_test(diff) # Normal distribution


gghistogram(df_w_2, x = "diff", y = "..density..", 
            fill = "steelblue",bins = 10, add_density = TRUE)


# Using one-tailed one-sample t-test 
t.test(df_w_2$diff, mu = 0, alternative = "greater")




# Effect size 

df_w_1 %>% cohens_d(diff ~ 1, mu = 0)

bxp_w_2 

```

```{r}
# Hypothesis 3



# Visualizing
bxp_w_3 <- ggboxplot(
  df_con$diff, width = 0.5, add = c("mean", "jitter"), 
  ylab = "Difference", xlab = "Inspiration"
  )+
  ggtitle("Boxplot of Inspiration Intervention")+
  theme_solarized()




bxp_w_3




df_con %>% 
  get_summary_stats(diff, type = "median_iqr")


# Normality
ggqqplot(df_con, x = "diff")

df_con %>% shapiro_test(diff) # Assuming no normal distribution


gghistogram(df_con, x = "diff", y = "..density..", 
            fill = "steelblue",bins = 10, add_density = TRUE)


# Using one-tailed one-sample  Wilcoxon test 
wilcox.test(df_con$diff, mu = 0, alternative = "greater") #significant




# Effect size 
df_con %>%  wilcox_effsize(diff ~ 1, mu = 0, alternative = "greater") # medium effect size



bxp_w_3


# Looking at inspiration without products out in the store 

df_only_con <- df_w_con

df_only_con$mean <- mean(df_only_con$diff, na.rm = T)
df_only_con$se <- std.error(df_only_con$diff, na.rm = T)

df_only_con$diff <- NULL # deleting original diff column

df_only_con$diff <- df_only_con$oms_con



sum(df_only_con$oms.y, na.rm = T) # 987
(3.57/987)*100 # 0.36% change

df_only_con$overall_inc <- as.character(df_only_con$overall_inc)
df_only_con$overall_inc <- "0.36 %"

df_only_con$mean <- round(df_only_con$mean, digits = 2)
df_only_con$se <- round(df_only_con$se, digits = 2)



df_only_con %>% 
  get_summary_stats(diff, type = "median_iqr")


# Normality
ggqqplot(df_only_con, x = "diff")

df_only_con %>% shapiro_test(diff) # Assuming no normal distribution


gghistogram(df_only_con, x = "diff", y = "..density..", 
            fill = "steelblue",bins = 10, add_density = TRUE)


# Using one-tailed one-sample  Wilcoxon test 
wilcox.test(df_only_con$diff, mu = 0, alternative = "greater") #significant



# Effect size 
df_only_con %>%  wilcox_effsize(diff ~ 1, mu = 0, alternative = "greater") # large effect size



```


```{r}
# Boxplot collection for H1, H2, H3 and H4


(bxp_w_1_out /bxp_w_2 ) | (bxp_w_3/bxp_lab_nug)


```



Hypothesis 4
```{r}


df_lab_nug <- read_csv("df_lab_nug.csv")



df_lab_nug$intervention <- as.factor(df_lab_nug$intervention)


df_lab_nug %>%
  group_by(intervention) %>%
  get_summary_stats(diff, type = "median_iqr")


# Visualizing data
bxp_lab_nug <- ggboxplot(
  df_lab_nug, x = "intervention", y = "diff", fill = "intervention",
  ylab = "Mean difference score", xlab = "Intervention", add = "jitter"
  )+
  ggtitle(" B) Comparing Nudging and Labeling")+
  theme_solarized()+
  scale_fill_brewer(palette="Blues")


bxp_lab_nug


# Normality
ggqqplot(df_lab_nug, x = "diff", facet.by = "intervention") # Not normal distributed


# Wilcoxon Rank Sum Test
df_lab_nug$intervention <- relevel(df_lab_nug$intervention, ref = "nudge")


wilcox_test(diff ~ intervention, alternative = "greater", data = df_lab_nug, paired = F) 



 # Effect size
wilcox_effsize(diff ~ intervention, alternative = "greater", data = df_lab_nug)

```


```{r}
# Does inspiration have a greater effect than the two other interventions

# Relevel intervention - inspiration as baseline
df$intervention <- as.factor(df$intervention)
df$intervention <- relevel(df$intervention, ref = "inspiration")



#df <- df_overall




m1 <- lm(diff ~ intervention, data = df)

summary(m1)

plot(m1)



# Normality
hist(df$diff)



plot(diff ~ intervention, data = df)




# Plotting the beta values
sjPlot::plot_model(m1, 
                   axis.labels=c("Nudging", "Labeling", "Intercept(Inspiration)"),
                   show.values=T, show.p=T, show.intercept = T,
                   title="Effect of Intervention on Climate-friendly Products - Measured in Difference score")


# Table of model summary
sjPlot::tab_model(m1, 
                  show.re.var= TRUE, show.se = T,
                  pred.labels =c("(Intercept)", "Labeling", "Nudging"),
                  dv.labels= "Effect of Intervention on Climate-friendly Products - Measured as Difference score")

summary(m1)


# Creating a model excluding products out in the store in the inspriation intervention

df_explorative <- bind_rows(df_w_1_out, df_w_2, df_only_con)

df_explorative$mean <- round(df_explorative$mean, digits = 2)
df_explorative$se <- round(df_explorative$se, digits = 2)

m2 <- lm(diff ~ intervention, data = df_explorative)


summary(m2)



explorative_plot <- df_explorative %>% 
  ggplot(aes(intervention, mean, fill = intervention, na.rm = T)) +
  geom_bar(stat = "summary")+
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.1,
                position=position_dodge(.9))+
  theme_solarized()+
  geom_text(aes(label = paste("",overall_inc, ", (", mean,")"), vjust = -0.4), , colour = "black", position = position_dodge(.9) )+
  labs(x = "Intervention", y = "Effect of interventions in % (absolute numbers)")+
  ggtitle("A) Intervention Effect on Purchase of Climate-friendly Products")+
  scale_fill_discrete(name = "Intervention Type")


explorative_plot



# Table of model summary for m2
sjPlot::tab_model(m2, 
                  show.re.var= TRUE, show.se = T,
                  pred.labels =c("(Intercept)", "Labeling", "Nudging"),
                  dv.labels= "Effect of Intervention on Climate-friendly Products - Measured as Difference score")

# Plotting the beta values for m2
sjPlot::plot_model(m2, 
                   axis.labels=c("Nudging", "Labeling", "Intercept(Inspiration)"),
                   show.values=T, show.p=T, show.intercept = T,
                   title="Effect of Intervention on Climate-friendly Products - Measured in Difference score")
```





```{r}



# Caulculating mean
df_w_1_out$mean <- mean(df_w_1_out$diff, na.rm = T)
df_w_2$mean <- mean(df_w_2$diff, na.rm = T)
df_w_3$mean <- mean(df_w_3$diff, na.rm = T)
df_con$mean <- mean(df_con$diff, na.rm = T)

# Calculating standard error 
df_w_1_out$se <- std.error(df_w_1_out$diff)
df_w_2$se <- std.error(df_w_2$diff, na.rm = T)
df_w_3$se <- std.error(df_w_3$diff, na.rm = T)
df_con$se <- std.error(df_con$diff, na.rm = T)

# Mean column in df_overall
df_overall[c(1:61), 15] <- df_w_1_out$mean
df_overall[c(62:68), 15] <- df_w_2$mean
df_overall[c(69:91), 15] <- df_w_3$mean
df_overall[c(92:114), 15] <- df_con$mean

# Standard error column in df_overall
df_overall[c(1:61), 14] <- df_w_1_out$se
df_overall[c(62:68), 14] <- df_w_2$se
df_overall[c(69:91), 14] <- df_w_3$se
df_overall[c(92:114), 14] <- df_con$se


# Mean column in df
df[c(1:61), 15] <- df_w_1_out$mean
df[c(62:68), 15] <- df_w_2$mean
df[c(69:91), 15] <- df_con$mean


#standard error column in df
df[c(1:61), 14] <- df_w_1_out$se
df[c(62:68), 14] <- df_w_2$se
df[c(69:91), 14] <- df_con$se


# Round decimals for df_overall
df_overall$mean <- round(df_overall$mean, digits = 2)
df_overall$se <- round(df_overall$se, digits = 2)

# Round decimals for df
df$mean <- round(df$mean, digits = 2) # Only convenience bags data in inspiration
df$se <- round(df$se, digits = 2)




```


```{r}

df_w_1_out <- read_csv("df_w_1_out.csv")
df_w_2 <- read_csv("df_w_2.csv")
df_w_3 <- read_csv("df_w_3.csv")
df_w_con <- read_csv("df_con.csv")



sum(df_w_1_out$oms.y, na.rm = T) # 3219
(-8.78/3219)*100 # -0.27% change

df_w_1_out$overall_inc <- as.character(df_w_1_out$overall_inc)
df_w_1_out$overall_inc <- "-0.27 %"

sum(df_w_2$oms.y) # 327
(7.14/327)*100 # 2.18%

df_w_2$overall_inc <- as.character(df_w_2$overall_inc)
df_w_2$overall_inc <- "2.18%"

sum(df_w_3$oms.y) # 987

(8.35/987)*100 #0.85%

df_w_3$overall_inc <- as.character(df_w_3$overall_inc)
df_w_3$overall_inc <- "0.85 %"

sum(df_w_con$oms.y) # 987
(4.78/987)*100 # 0.48%

df_w_con$overall_inc <- as.character(df_w_con$overall_inc)
df_w_con$overall_inc <- "0.48 %"

df_overall$overall_inc <- "J"

df_overall[c(1:61), 17] <- df_w_1_out$overall_inc
df_overall[c(62:68), 17] <- df_w_2$overall_inc
df_overall[c(69:91), 17] <- df_w_3$overall_inc
df_overall[c(92:114), 17] <- df_w_con$overall_inc


```

Visualizing 
```{r}

# Plot of the three interventions

df_plot <- df_overall %>% 
  ggplot(aes(intervention, mean, fill = int_type, na.rm = T)) +
  geom_bar(position = "dodge", stat = "summary")+
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.1,
                position=position_dodge(.9))+
  theme_solarized()+
  geom_text(aes(label = paste("",overall_inc, ", (", mean,")"), vjust = -0.4), , colour = "black", position = position_dodge(.9) )+
  labs(x = "Intervention", y = "Effect of interventions in % (absolute numbers)")+
  ggtitle("A) Intervention Effect on Purchase of Climate-friendly Products")+
  scale_fill_discrete(name = "Intervention Type")



df_plot

df_plot+ bxp_lab_nug
```

Explorative plot
```{r}

df_overall[c(69:91), 12] <- df_w_3$diff_con " Difference score for numbers entailing supermarket and bags"
df_overall[c(69:91), 14] <- "Store + Convenience bags"
df_overall[c(69:91), 16] <- mean(df_w_3$diff_con) # Mean
df_overall[c(69:91), 15] <- std.error(df_w_3$diff_con) # Standard error

df_overall$mean <- round(df_overall$mean, digits = 2)
df_overall$se <- round(df_overall$se, digits = 2)


sum(df_w_3$oms_con_total) # 1179
(8.35/1179)*100 # 0.71%

df_overall[c(69:91), 17] <- "0.71 %"


df_overall[c(92:114), 12] <- df_w_con$oms_con
df_overall[c(92:114), 14] <- "Convenience bags"
df_overall[c(92:114), 16] <- mean(df_w_con$oms_con) # Mean
df_overall[c(92:114), 15] <- std.error(df_w_con$oms_con) # Standard error

df_overall$mean <- round(df_overall$mean, digits = 2)
df_overall$se <- round(df_overall$se, digits = 2)

sum(df_w_3$oms_con_total) # 1179
(3.57/1179)*100 # 0.30%





df_plot_1 <- df_overall %>% 
  ggplot(aes(intervention, mean, fill = int_type, na.rm = T)) +
  geom_bar(position = "dodge", stat = "summary")+
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.1,
                position=position_dodge(.9))+
  theme_solarized()+
  geom_text(aes(label = paste("",overall_inc, ", (", mean,")"), vjust = -0.4), , colour = "black", position = position_dodge(.9) )+
  labs(x = "Intervention", y = "Effect of interventions in % (absolute numbers)")+
  ggtitle("A) Intervention Effect on Purchase of Climate-friendly Products")+
  scale_fill_discrete(name = "Intervention Type")

df_plot_1

```

