---
title: "Coop_bachelor"
author: "Julie Svinth Nielsen"
date: "18/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readr)
library(lme4)
library(lmerTest)
```

Load in data and pre-process
```{r}

df_ref <- read_delim("Klimaprojekt tal 23.9 - 6.9.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)

df <- read_delim("Klimaprojekt tal 7.10 - 13.10.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)
View(df)

nudge  <- read_delim("Kopi af salgstals klimaprojekt 14.10 - 20.10.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)

nudge <- nudge[-c(1, 2, 3, 12), ]


### Der skal laves en kolonne, der inddeler dem i varegrupper

# Removing three first rows
df <- df[-c(1, 2, 3), ]

```

Creating ID column and product column
```{r}

df$ID <- seq.int(nrow(df))
df <- df[-c(66),]

df_40 <- filter(df, uge == "Uge 2021-40")

df_40 <- select(df_40, -c(1,6:14))

df_40$prod_cat<- c("j") 
df_40[c(1,10,57,61), 5] <- c("water")
df_40[c(2,46,62), 5] <- c("beats")
df_40[c(4,51), 5] <- c("onion")
df_40[c(3,7,11,13,21,38,47), 5] <- c("cale")
df_40[c(22,32), 5] <- c("squash")
df_40[c(64), 5] <- c("chickpea")
df_40[c(26,34,54), 5] <- c("apples")
df_40[c(18,43,53), 5] <- c("pear")
df_40[c(14), 5] <- c("berries")
df_40[c(23,45,65), 5] <- c("broccoli")
df_40[c(20,63), 5] <- c("spinage")
df_40[c(5,9,24,25,31,41,42,48,49,55), 5] <- c("potato")
df_40[c(4,19,30,33,36,37,50,52), 5] <- c("tomato")
df_40[c(16,35,56,60), 5] <- c("flour")
df_40[c(17,40), 5] <- c("mushrooms")
df_40[c(28,29,39,44), 5] <- c("carrots")
df_40[c(6), 5] <- c("celeriac")
df_40[c(8,15), 5] <- c("leek")
df_40[c(12), 5] <- c("bread")
df_40[c(27), 5] <- c("plums")
df_40[c(58,59), 5] <- c("corn")


df_ref$ID <- seq.int(nrow(df_ref))

# Create df with week 41
df_41 <- filter(df, uge == "Uge 2021-41")

df_41 <- select(df_41, -c(1,6:14))


df_41$prod_cat<- c("j") 
df_41[c(1,10,57,61), 5] <- c("water")
df_41[c(2,46,62), 5] <- c("beats")
df_41[c(4,51), 5] <- c("onion")
df_41[c(3,7,11,13,21,38,47), 5] <- c("cale")
df_41[c(22,32), 5] <- c("squash")
df_41[c(64), 5] <- c("chickpea")
df_41[c(26,34,54), 5] <- c("apples")
df_41[c(18,43,53), 5] <- c("pear")
df_41[c(14), 5] <- c("berries")
df_41[c(23,45,65), 5] <- c("broccoli")
df_41[c(20,63), 5] <- c("spinage")
df_41[c(5,9,24,25,31,41,42,48,49,55), 5] <- c("potato")
df_41[c(4,19,30,33,36,37,50,52), 5] <- c("tomato")
df_41[c(16,35,56,60), 5] <- c("flour")
df_41[c(17,40), 5] <- c("mushrooms")
df_41[c(28,29,39,44), 5] <- c("carrots")
df_41[c(6), 5] <- c("celeriac")
df_41[c(8,15), 5] <- c("leek")
df_41[c(12), 5] <- c("bread")
df_41[c(27), 5] <- c("plums")
df_41[c(58,59), 5] <- c("corn")


write.csv(x=df_40, file="df_40.csv")
write.csv(x=df_41, file="df_41.csv")

```

## Reference week

```{r}

df_ref <- df_ref[-c(1, 2, 3),]

df_ref <- df_ref[-c(65),]
df_ref <- df_ref[-c(130),]
df_ref$prod_cat<- c("j") 
df_ref <- select(df_ref, -c(1,6:14))


df_38_ref <- filter(df_ref, uge == "Uge 2021-38")
df_39_ref <- filter(df_ref, uge == "Uge 2021-39")
df_40_ref <- filter(df_ref, uge == "Uge 2021-40")


df_38_ref[c(1,10, 56, 60), 5] <- c("water")
df_38_ref[c(2, 45, 61), 5] <- c("beats")
df_38_ref[c(4,50), 5] <- c("onion")
df_38_ref[c(3,7,11,13,21, 37, 46), 5] <- c("cale")
df_38_ref[c(22, 31), 5] <- c("squash")
df_38_ref[c(63), 5] <- c("chickpea")
df_38_ref[c(26, 33, 53), 5] <- c("apples")
df_38_ref[c(18, 42, 52), 5] <- c("pear")
df_38_ref[c(14), 5] <- c("berries")
df_38_ref[c(23, 44, 64), 5] <- c("broccoli")
df_38_ref[c(20, 62), 5] <- c("spinage")
df_38_ref[c(5,9,24,25,30, 40, 41, 47, 48, 54), 5] <- c("potato")
df_38_ref[c(4,19,29, 32, 35, 36, 49, 51), 5] <- c("tomato")
df_38_ref[c(16, 34, 55, 59), 5] <- c("flour")
df_38_ref[c(17, 39), 5] <- c("mushrooms")
df_38_ref[c(28, 38, 43), 5] <- c("carrots")
df_38_ref[c(6), 5] <- c("celeriac")
df_38_ref[c(8,15), 5] <- c("leek")
df_38_ref[c(12), 5] <- c("bread")
df_38_ref[c(27), 5] <- c("plums")
df_38_ref[c(57, 58), 5] <- c("corn")

write.csv(x=df_38_ref, file="df_38_ref.csv")


df_39_ref[c(1,10, 57, 61), 5] <- c("water")
df_39_ref[c(2, 46, 62), 5] <- c("beats")
df_39_ref[c(4, 51), 5] <- c("onion")
df_39_ref[c(3,7,11,13,21, 38, 47), 5] <- c("cale")
df_39_ref[c(22, 32), 5] <- c("squash")
df_39_ref[c(64), 5] <- c("chickpea")
df_39_ref[c(26, 34, 54), 5] <- c("apples")
df_39_ref[c(18, 43, 53), 5] <- c("pear")
df_39_ref[c(14), 5] <- c("berries")
df_39_ref[c(23, 45, 65), 5] <- c("broccoli")
df_39_ref[c(20, 63), 5] <- c("spinage")
df_39_ref[c(5,9,24,25, 31, 41, 42, 48, 49, 55), 5] <- c("potato")
df_39_ref[c(4,19, 30, 33, 36, 37, 50, 52), 5] <- c("tomato")
df_39_ref[c(16, 35, 56, 60), 5] <- c("flour")
df_39_ref[c(17, 40), 5] <- c("mushrooms")
df_39_ref[c(28, 29, 39, 44), 5] <- c("carrots")
df_39_ref[c(6), 5] <- c("celeriac")
df_39_ref[c(8,15), 5] <- c("leek")
df_39_ref[c(12), 5] <- c("bread")
df_39_ref[c(27), 5] <- c("plums")
df_39_ref[c(58, 59), 5] <- c("corn")

write.csv(x=df_39_ref, file="df_39_ref.csv")



df_40_ref[c(1,10, 55, 59), 5] <- c("water")
df_40_ref[c(2, 44, 60), 5] <- c("beats")
df_40_ref[c(4, 49), 5] <- c("onion")
df_40_ref[c(3,7,11,13,21, 36, 45), 5] <- c("cale")
df_40_ref[c(22, 31), 5] <- c("squash")
df_40_ref[c(62), 5] <- c("chickpea")
df_40_ref[c(26, 52), 5] <- c("apples")
df_40_ref[c(18, 41, 51), 5] <- c("pear")
df_40_ref[c(14), 5] <- c("berries")
df_40_ref[c(23,43, 63), 5] <- c("broccoli")
df_40_ref[c(20,61), 5] <- c("spinage")
df_40_ref[c(5,9,24,25,30, 39, 40, 46, 47, 53), 5] <- c("potato")
df_40_ref[c(4,19,29, 32, 34, 35, 48, 50), 5] <- c("tomato")
df_40_ref[c(16,33, 54, 58), 5] <- c("flour")
df_40_ref[c(17, 38), 5] <- c("mushrooms")
df_40_ref[c(28,37, 42), 5] <- c("carrots")
df_40_ref[c(6), 5] <- c("celeriac")
df_40_ref[c(8,15), 5] <- c("leek")
df_40_ref[c(12), 5] <- c("bread")
df_40_ref[c(27), 5] <- c("plums")
df_40_ref[c(56, 57), 5] <- c("corn")

write.csv(x=df_40_ref, file="df_40_ref.csv")


# Nudge dataframe

nudge$prod_cat<- c("j") 

nudge[c(1, 9), 5] <- c("squash")
nudge[c(3, 11), 5] <- c("tomato")
nudge[c(2, 10), 5] <- c("carrots")
nudge[c(4, 7, 12, 15), 5] <- c("broccoli")
nudge[c(5, 8, 13, 16), 5] <- c("spinage")
nudge[c(6, 14), 5] <- c("chickpea")
nudge$intervention <- "nudge"



df_reference <- read_csv("df_reference.csv")

df_reference <- df_reference %>% 
  rename(
    X3 = X4.x
    )

write.csv(x=df_reference, file="df_reference.csv")

nudge$vare <- as.numeric(nudge$vare)

# create two df with 41 and 42 - add the two oms
nudge_41 <- subset(nudge, uge == "Uge 2021-41")
nudge_42 <- subset(nudge, uge == "Uge 2021-42")

nudge_new <- nudge_41 %>% 
  left_join(nudge_42, by = "vare")

nudge_new$oms_new <- nudge_new$oms.x + nudge_new$oms.y

nudge_new <- select(nudge_new, -c(4))

# Create new dataframe where products that appear in the nudge df is combined together with the same products from df_reference - only showing the exact same products - below eachother 


test <- subset(df_reference, vare== 5700382516469 | vare == 5700383878061 | vare== 5750006326691 | vare== 7340011481782 | vare== 7340011487906 | vare== 7340191112582) 

test <- subset(df_reference, vare== 5700382815340) #not in the reference week data
test <- subset(df_reference, vare== 7340191112711) #not in the reference week data

test <- select(test, -c(1))

nudge_new <- nudge_new %>% 
  rename(
    oms = oms_new
    )

nudge_new$prod_cat<- c("j") 

nudge_new[c(1), 6] <- c("squash")
nudge_new[c(3), 6] <- c("tomato")
nudge_new[c(2), 6] <- c("carrots")
nudge_new[c(4, 7), 6] <- c("broccoli")
nudge_new[c(5, 8), 6] <- c("spinage")
nudge_new[c(6), 6] <- c("chickpea")




df_ref_nudge <- bind_rows(nudge_new, test, .id = "uge")


write.csv(x=df_ref_nudge, file="df_ref_nudge.csv")

#df_ref_nudge <- read_csv("df_ref_nudge.csv")
#df_ref_nudge <- df_ref_nudge[-c(2), ]

df_ref_nudge[c(14), 1] <- NA

df_ref_nudge$vare <- as.numeric(df_ref_nudge$vare)
df_ref_nudge$oms <- as.numeric(df_ref_nudge$oms)

df_ref_nudge[c(14), 1] <- 14
df_ref_nudge[c(14), 2] <- 2
df_ref_nudge[c(14), 3] <- 7340191112711
df_ref_nudge[c(14), 4] <- "Coop HK spinat 1kg"
df_ref_nudge[c(14), 5] <- "reference"
df_ref_nudge[c(14), 6] <- 10
df_ref_nudge[c(14), 7] <- "spinage"

```

```{r}
# Creating intervention column 
df_38_ref$intervention <- "reference"
df_39_ref$intervention <- "reference"
df_40_ref$intervention <- "reference"
df_40$intervention <- "label"
df_41$intervention <- "label"

```

```{r}

# Create oms for the entire week 
df_ref_first <- df_38_ref %>% 
  left_join(df_39_ref, by = "vare")

df_ref_first$oms_new <- df_ref_first$oms.x + df_ref_first$oms.y

df_ref_final <- df_ref_first %>% 
  left_join(df_40_ref, by = "vare")

df_ref_final$oms_final <- df_ref_final$oms_new + df_ref_final$oms

df_ref_final <- select(df_ref_final, -c(7:17))

df_ref_final[c(4), 5] <- c("onion")

# Making an average of the two weeks to create the reference week
df_ref_final$oms_ref <- df_ref_final$oms_final/2

df_ref_final$oms_ref <- round(df_ref_final$oms_ref, digits = 0)


write.csv(x=df_ref_final, file="df_reference.csv")

df_reference <- read_csv("~/Uni stuff/Bachelor/bachelor/df_reference.csv")


#df_label <- df_40 %>% 
  #left_join(df_41, by = "Vare")

df_label$oms_new <- df_label$oms.x + df_label$oms.y

df_label <- select(df_label, -c(8:13))

df_label[c(4), 5] <- c("onion")



df_label <- df_label %>% 
  rename(
    oms = oms_new
    )

df_label <- select(df_label, -c(6))
df_ref_final <- select(df_ref_final, -c(7))

write.csv(x=df_label, file="df_label.csv")

df_ref_final <- df_ref_final %>% 
  rename(
    oms = oms_ref
    )

# On top of eachother

df_ref_label <- bind_rows(df_ref_final, df_label, .id = "uge.x")


# Final csv for dataframe containing numbers from reference week and first intervention

write.csv(x=df_ref_label, file="df_ref_label.csv")



```

## Visualization

```{r}


illustration_test <- df_ref_label %>%
  filter(prod_cat.x %in% c("cale", "spinage", "squash")) %>% 
  ggplot(aes(prod_cat.x, oms, fill = intervention.x))+geom_bar( stat = "summary", position = "dodge")+ 
  xlab("something")+ ylab("something")

illustration_test



illustration_test_1 <- coop %>%
  ggplot(aes(intervention.x, oms))+geom_bar( stat = "summary", position = "dodge")+ 
  xlab("something")+ ylab("something")

illustration_test_1






illustration_test_12 <- df_ref_nudge %>%
  filter(!(X3 %in% c("<d8>ko 365 Guler<f8>dder 1", "Coop HK spinat 1kg"))) %>% 
  ggplot(aes(intervention, oms))+geom_bar( stat = "summary", position = "dodge")+ 
  xlab("something")+ ylab("something")

illustration_test_12

```


```{r}

#coop <- read_csv("~/Uni stuff/Bachelor/bachelor/df_ref_label.csv")
```


```{r}
#coop$week <- 1
#df_ref_nudge$week <- 1

#make common columns 
#coop <- coop %>% 
  #rename(
    #intervention = intervention.x,
    prod_cat = prod_cat.x,
    X3 = X4.x,
    uge = uge.x
    )

write.csv(x=coop, file="coop.csv")


coop$vare_grp<- c("j") 
coop[c(2:9, 11, 13, 15,  17, 19:25, 28:32, 35:41, 43:51, 54, 61, 62, 64, 66:73, 75, 77, 79, 81, 83:89, 92:97, 100:106, 108:116, 119, 126, 127, 129), 9] <- c("vegetables")
coop[c(14, 18, 26, 27, 33, 42, 52, 53, 78, 82, 90, 91, 98, 107, 117, 118), 9] <- c("fruit")
coop[c(57, 58, 63, 122, 123, 128), 9] <- c("canned")
coop[c(12, 16, 34, 55, 59, 76, 80, 99, 120, 124), 9] <- c("bread/flour")
coop[c(1, 10, 56, 60, 65, 74, 121, 125), 9] <- c("water")


df_ref_nudge$week <- 2
df_ref_nudge$vare_grp<- c("j") 
df_ref_nudge[c(1:4, 6:11, 13, 14), 9] <- c("vegetables")
df_ref_nudge[c(5, 12), 9] <- c("canned")



df_big <- bind_rows(coop, df_ref_nudge, .id = "uge")

write.csv(x=df_big, file="df_big.csv")

```

```{r}
# Illustrate df_big

df_big$intervention <- as.factor(df_big$intervention)
df_big$week <- as.factor(df_big$week)



df_big_plot <- df_big %>%
  filter(!(X3 %in% c("<d8>ko 365 Guler<f8>dder 1", "Coop HK spinat 1kg"))) %>% 
  ggplot(aes(week, oms, fill = intervention))+geom_bar( stat = "summary", position = "dodge")+ 
  xlab("Intervention week")+ ylab("Mean of sold products")

df_big_plot

```


Building model
```{r}



# Making products and intervention into factors
coop$prod_cat <- as.factor(coop$prod_cat)
coop$intervention <- as.factor(coop$intervention)

m0 <- lm(oms  ~ intervention, data = coop, REML = FALSE)
m1 <- lmer(oms  ~ intervention + (1|prod_cat), data = coop, REML = FALSE)

summary(m0)
summary(m1)

plot(m1)

```
```{r}
inspiration <- read_delim("inspiration.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)

inspiration[,6] <- c("inspiration")
inspiration[,7] <- c(3)


inspiration_ref <- read_delim("inspiration_ref.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)

inspiration_ref[,6] <- c("reference")
inspiration_ref[,7] <- c(3)



df_insp_only <- bind_rows(inspiration_ref, inspiration, .id = "uge")



df_insp_only$prod_cat <- "j"


df_insp_only$vare_grp <- "j"
df_insp_only[c(2, 3, 5, 9:13, 15, 16, 25, 26, 28, 32:36, 38, 39), 8] <- c("vegetable")
df_insp_only[c(18, 19, 41, 42), 8] <- c("canned")
df_insp_only[c(4, 6, 27, 29), 8] <- c("herbes")
df_insp_only[c(20, 21, 43, 44), 8] <- c("spices")
df_insp_only[c(1, 22, 24, 45), 8] <- c("cheese")
df_insp_only[c(14, 17, 37, 40), 8] <- c("pasta_stuff")
df_insp_only[c(7, 23, 30, 46), 8] <- c("boullion/seed")

df_big$week <- as.numeric(df_big$week)

df_big_final <- bind_rows(df_big, df_insp_only, .id = "uge")

```



```{r}

df_big__final_plot <- df_big_final %>%
  ggplot(aes(week, oms, fill = intervention))+geom_bar( stat = "summary", position = "dodge")+ 
  xlab("Intervention week")+ ylab("Mean of sold products")

df_big__final_plot
```

