---
title: "sporgeskema"
author: "Julie Svinth Nielsen"
date: "19/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
library(tidyverse)
library(readr)
library(dplyr)
library(plyr)
```

Load in data
```{r}

spg <- read_delim("complete.csv", ";", 
    escape_double = FALSE, trim_ws = TRUE)

```
Create ID
```{r}
spg$ID <- seq.int(nrow(spg))

# Make all answers numeric perhaps? Give them the number from 1 to 5
spg[spg == "Enig"] <- "5"
spg[spg == "Delvis enig"] <- "4"
spg[spg == "Hverken eller"] <- "3"
spg[spg == "Delvis uenig"] <- "2"
spg[spg == "Uenig"] <- "1"

df <- spg



df_2 <- gather(df, factor, response, intro_1:nudge_4, factor_key = TRUE)



df_2 <- df_2 %>% 
  mutate(category = substr(factor, 1,4)) %>% 
  mutate(category = as.factor(category))

df_2$category <- revalue(df_2$category, c("intr" = "introduction", "oply" = "oplysning", "insp" = "inspiration", "nudg"="nudging"))




```

Illustration
```{r}

# Illustrate the different groups and the answers within this area - intro, oplysning, inspiration, nudging.

df_2 %>% 
  filter(factor == "intro_1") %>% 
  ggplot(aes(as.factor(response), fill = response))+geom_bar()

df_2 %>% 
  filter(factor %in% c("intro_2", "intro_3", "intro_4", "intro_5")) %>% 
  ggplot(aes(factor, as.numeric(response), fill = factor))+geom_bar( stat = "summary")




```

intro_2: Jeg går op i at handle klimavenligt 

intro_3:Jeg prioriterer lavere priser over det klimabevidste valg 

intro_4:Jeg er villig til at ændre mine indkøbsvaner, så de bliver mere klimavenlige 

intro_5:Der er så mange hensyn at tage i forhold til indkøb, så jeg prioriterer ikke klimaet  

```{r}
df_2 %>% 
  filter(category %in% c("oplysning", "inspiration", "nudging")) %>% 
  ggplot(aes(category, as.numeric(response), fill = category))+geom_bar( stat = "summary")

df_2 %>% 
  filter(category %in% c("oplysning", "inspiration", "nudging")) %>% 
  mutate(response = as.numeric(response)) %>% 
  group_by(category) %>% 
  dplyr::summarise(mean = mean(response, na.rm = TRUE))

```
```{r}
df_2 %>% 
  filter(category %in% c("oplysning", "inspiration", "nudging")) %>% 
  ggplot(aes(factor, as.numeric(response), fill = category))+geom_bar(stat = "summary")
  
```

